<script setup lang="ts">
let value = ref('');
</script>

<template>
    <lew-flex style="width: 300px" gap="20px" x="start" direction="y">
        <lew-textarea
            v-model="value"
            placeholder="可清空的"
            :max-length="300"
            show-count
            clearable
        />
        <lew-textarea
            v-model="value"
            placeholder="只读"
            :max-length="300"
            show-count
            readonly
            clearable
        />
        <lew-textarea
            v-model="value"
            placeholder="禁用"
            :max-length="300"
            show-count
            disabled
            clearable
        />
        <lew-textarea
            v-model="value"
            placeholder="自由缩放"
            :max-length="12"
            width="300px"
            height="100px"
            show-count
            clearable
            resize="both"
        />
        <lew-textarea
            v-model="value"
            placeholder="垂直缩放"
            :max-length="12"
            show-count
            clearable
            resize="vertical"
        />
        <lew-textarea
            v-model="value"
            width="300px"
            placeholder="横向缩放"
            :max-length="12"
            show-count
            clearable
            resize="horizontal"
        />
    </lew-flex>
</template>
