<template>
  <lew-flex wrap x="start" y="end" gap="20">
    <lew-avatar
      :size="30"
      src="https://api.lew.kamtao.com/manage/common/avatar/550/4B78CA/王"
      alt="avatar"
    />
    <lew-avatar
      :size="40"
      src="https://api.lew.kamtao.com/manage/common/avatar/350/4B78CA/李"
      alt="avatar"
    />
    <lew-avatar
      :size="50"
      src="https://api.lew.kamtao.com/manage/common/avatar/1000/4B78CA/张"
      alt="avatar"
    />
  </lew-flex>
</template>
