<template>
  <lew-flex wrap x="start" gap="20">
    <lew-avatar
      src="https://api.lew.kamtao.com/manage/common/avatar/550/4B78CA/杨"
      status="online"
      status-position="top-left"
    />
    <lew-avatar
      src="https://api.lew.kamtao.com/manage/common/avatar/550/4B78CA/陶"
      status="processing"
      status-position="top-left"
    />
    <lew-avatar
      src="https://api.lew.kamtao.com/manage/common/avatar/550/4B78CA/卢"
      status="busy"
      status-position="top-right"
    />
    <lew-avatar
      src="https://api.lew.kamtao.com/manage/common/avatar/550/4B78CA/黄"
      round
      status="away"
      status-position="bottom-left"
    />
    <lew-avatar
      src="https://api.lew.kamtao.com/manage/common/avatar/550/4B78CA/王"
      round
      status="offline"
      status-position="bottom-right"
    />
  </lew-flex>
</template>
