export default {
  name: 'es',
  image: {
    fail: 'No se puede cargar la imagen, por favor inténtelo de nuevo más tarde',
  },
  input: {
    placeholder: 'Por favor, introduzca',
    copy: 'Copiar',
    copySuccess: 'Copiado al portapapeles',
    copyFailed: 'Error al copiar, por favor inténtelo de nuevo',
  },
  inputTag: {
    placeholder: 'Escriba y presione Enter para añadir una etiqueta',
    maxLength:
      'Ha alcanzado el límite de {maxLength} etiquetas, elimine algunas para continuar añadiendo',
    duplicate: 'Esta etiqueta ya existe, por favor introduzca una nueva',
  },
  select: {
    placeholder: 'Por favor, seleccione',
    resultCount: '{num} resultados',
    noResult: 'Sin resultados',
    searchPlaceholder: 'Introduzca palabras clave',
  },
  selectMultiple: {
    placeholder: 'Por favor, seleccione',
    resultCount: '{num} resultados',
    noResult: 'Sin resultados',
    searchPlaceholder: 'Introduzca palabras clave',
  },
  cascader: {
    placeholder: 'Por favor, seleccione',
    closeText: 'Cerrar',
    okText: 'Aceptar',
    noResult: 'Sin resultados',
  },
  tree: {
    resultCount: '{num} resultados',
    noResult: 'Sin resultados',
    searchPlaceholder: 'Introduzca palabras clave',
  },
  treeSelect: {
    placeholder: 'Por favor, seleccione',
  },
  textarea: {
    placeholder: 'Por favor, introduzca',
    resizeHandle: 'Arrastrar para redimensionar',
  },
  inputNumber: {
    placeholder: 'Por favor, introduzca',
  },
  datePicker: {
    Mon: 'Lun',
    Tue: 'Mar',
    Wed: 'Mié',
    Thu: 'Jue',
    Fri: 'Vie',
    Sat: 'Sáb',
    Sun: 'Dom',
    Jan: 'Ene',
    Feb: 'Feb',
    Mar: 'Mar',
    Apr: 'Abr',
    May: 'May',
    Jun: 'Jun',
    Jul: 'Jul',
    Aug: 'Ago',
    Sep: 'Sep',
    Oct: 'Oct',
    Nov: 'Nov',
    Dec: 'Dic',
    placeholder: 'Seleccionar fecha',
  },
  dateRangePicker: {
    placeholderStart: 'Fecha de inicio',
    placeholderEnd: 'Fecha de fin',
  },
  drawer: {
    closeText: 'Cerrar',
    okText: 'Aceptar',
    confirmText: 'Confirmar',
  },
  modal: {
    closeText: 'Cerrar',
    okText: 'Aceptar',
    confirmText: 'Confirmar',
  },
  dialog: {
    cancelText: 'Cancelar',
    okText: 'Aceptar',
    confirmText: 'Confirmar',
  },
  popok: {
    cancelText: 'Cancelar',
    okText: 'Aceptar',
    confirmText: 'Confirmar',
  },
  colorPicker: {
    placeholder: 'Por favor, introduzca',
  },
  upload: {
    dropActive: 'Suelte para comenzar la carga',
    click: 'Haga clic para cargar, ',
    paste: 'pegue, ',
    drag: 'o arrastre archivos aquí',
    accept: 'Admite la carga de {accept}',
    limit: 'Se pueden cargar un máximo de {limit} archivos',
    maxFileSize: 'Cada archivo no debe exceder {maxFileSize}',
    pending: 'Pendiente',
    success: 'Carga exitosa',
    fail: 'Error en la carga',
    uploading: 'Cargando',
    complete: 'Cargado',
    wrong_type: 'Formato inválido',
    wrong_size: 'El tamaño del archivo excede el límite',
  },
  pagination: {
    pageSize: '{pageSize} por página',
    jumpTo: 'Pág.',
    jumpConfirm: 'Ir',
    summary: 'Página {current} de {totalPages} · {total} elementos',
    perPage: 'Por página',
    prevSection: 'Páginas anteriores',
    nextSection: 'Páginas siguientes',
    navLabel: 'Paginación',
    jumpGroup: 'Ir a la página',
    prevPage: 'Página anterior',
    nextPage: 'Página siguiente',
  },
  contextMenu: {
    noActions: 'No hay acciones disponibles',
  },
  empty: {
    title: 'Sin datos',
  },
}
