export default {
  name: 'fr',
  image: {
    fail: 'Impossible de charger l\'image pour le moment, veuillez réessayer plus tard',
  },
  input: {
    placeholder: 'Veuillez saisir',
    copy: 'Copier',
    copySuccess: 'Copié dans le presse-papiers',
    copyFailed: 'La copie a échoué, veuillez réessayer',
  },
  inputTag: {
    placeholder: 'Saisissez une étiquette et appuyez sur Entrée pour l\'ajouter',
    maxLength:
      'Vous avez atteint la limite de {maxLength} étiquettes, supprimez-en quelques-unes pour continuer',
    duplicate: 'Cette étiquette existe déjà, veuillez en saisir une nouvelle',
  },
  select: {
    placeholder: 'Veuillez sélectionner',
    resultCount: '{num} résultats',
    noResult: 'Aucun résultat',
    searchPlaceholder: 'Entrez les mots-clés de recherche',
  },
  selectMultiple: {
    placeholder: 'Veuillez sélectionner',
    resultCount: '{num} résultats',
    noResult: 'Aucun résultat',
    searchPlaceholder: 'Entrez les mots-clés de recherche',
  },
  cascader: {
    placeholder: 'Veuillez sélectionner',
    closeText: 'Fermer',
    okText: 'OK',
    noResult: 'Aucun résultat',
  },
  tree: {
    resultCount: '{num} résultats',
    noResult: 'Aucun résultat',
    searchPlaceholder: 'Entrez les mots-clés de recherche',
  },
  treeSelect: {
    placeholder: 'Veuillez sélectionner',
  },
  textarea: {
    placeholder: 'Veuillez saisir',
    resizeHandle: 'Glisser pour redimensionner',
  },
  inputNumber: {
    placeholder: 'Veuillez saisir',
  },
  datePicker: {
    Mon: 'Lun',
    Tue: 'Mar',
    Wed: 'Mer',
    Thu: 'Jeu',
    Fri: 'Ven',
    Sat: 'Sam',
    Sun: 'Dim',
    Jan: 'Janv',
    Feb: 'Févr',
    Mar: 'Mars',
    Apr: 'Avr',
    May: 'Mai',
    Jun: 'Juin',
    Jul: 'Juil',
    Aug: 'Août',
    Sep: 'Sept',
    Oct: 'Oct',
    Nov: 'Nov',
    Dec: 'Déc',
    placeholder: 'Sélectionner une date',
  },
  dateRangePicker: {
    placeholderStart: 'Date de début',
    placeholderEnd: 'Date de fin',
  },
  drawer: {
    closeText: 'Fermer',
    okText: 'OK',
    confirmText: 'Confirmer',
  },
  modal: {
    closeText: 'Fermer',
    okText: 'OK',
    confirmText: 'Confirmer',
  },
  dialog: {
    cancelText: 'Annuler',
    okText: 'OK',
    confirmText: 'Confirmer',
  },
  popok: {
    cancelText: 'Annuler',
    okText: 'OK',
    confirmText: 'Confirmer',
  },
  colorPicker: {
    placeholder: 'Veuillez saisir',
  },
  upload: {
    dropActive: 'Relâchez pour commencer le téléchargement',
    click: 'Cliquez pour télécharger, ',
    paste: 'collez, ',
    drag: 'ou faites glisser les fichiers ici',
    accept: 'Prend en charge le téléchargement de {accept}',
    limit: 'Vous pouvez télécharger jusqu\'à {limit} fichiers',
    maxFileSize: 'Chaque fichier ne doit pas dépasser {maxFileSize}',
    pending: 'En attente',
    success: 'Téléchargement réussi',
    fail: 'Échec du téléchargement',
    uploading: 'Téléchargement en cours',
    complete: 'Téléchargé',
    wrong_type: 'Format invalide',
    wrong_size: 'La taille du fichier dépasse la limite',
  },
  pagination: {
    pageSize: '{pageSize} par page',
    jumpTo: 'Aller à',
  },
  contextMenu: {
    noActions: 'Aucune action disponible',
  },
  empty: {
    title: 'Aucune donnée',
  },
}
