export default {
  name: 'it',
  image: {
    fail: 'Impossibile caricare l\'immagine, si prega di riprovare più tardi',
  },
  input: {
    placeholder: 'Inserisci',
    copy: 'Copia',
    copySuccess: 'Copiato negli appunti',
    copyFailed: 'Copia fallita, si prega di riprovare',
  },
  inputTag: {
    placeholder: 'Digita e premi Invio per aggiungere un tag',
    maxLength:
      'Hai raggiunto il limite di {maxLength} tag, rimuovine alcuni per continuare',
    duplicate: 'Questo tag esiste già, inserisci un nuovo tag',
  },
  select: {
    placeholder: 'Seleziona',
    resultCount: '{num} risultati',
    noResult: 'Nessun risultato',
    searchPlaceholder: 'Inserisci parole chiave',
  },
  selectMultiple: {
    placeholder: 'Seleziona',
    resultCount: '{num} risultati',
    noResult: 'Nessun risultato',
    searchPlaceholder: 'Inserisci parole chiave',
  },
  cascader: {
    placeholder: 'Seleziona',
    closeText: 'Chiudi',
    okText: 'OK',
    noResult: 'Nessun risultato',
  },
  tree: {
    resultCount: '{num} risultati',
    noResult: 'Nessun risultato',
    searchPlaceholder: 'Inserisci parole chiave',
  },
  treeSelect: {
    placeholder: 'Seleziona',
  },
  textarea: {
    placeholder: 'Inserisci',
    resizeHandle: 'Trascina per ridimensionare',
  },
  inputNumber: {
    placeholder: 'Inserisci',
  },
  datePicker: {
    Mon: 'Lun',
    Tue: 'Mar',
    Wed: 'Mer',
    Thu: 'Gio',
    Fri: 'Ven',
    Sat: 'Sab',
    Sun: 'Dom',
    Jan: 'Gen',
    Feb: 'Feb',
    Mar: 'Mar',
    Apr: 'Apr',
    May: 'Mag',
    Jun: 'Giu',
    Jul: 'Lug',
    Aug: 'Ago',
    Sep: 'Set',
    Oct: 'Ott',
    Nov: 'Nov',
    Dec: 'Dic',
    placeholder: 'Seleziona data',
  },
  dateRangePicker: {
    placeholderStart: 'Data iniziale',
    placeholderEnd: 'Data finale',
  },
  drawer: {
    closeText: 'Chiudi',
    okText: 'OK',
    confirmText: 'Conferma',
  },
  modal: {
    closeText: 'Chiudi',
    okText: 'OK',
    confirmText: 'Conferma',
  },
  dialog: {
    cancelText: 'Annulla',
    okText: 'OK',
    confirmText: 'Conferma',
  },
  popok: {
    cancelText: 'Annulla',
    okText: 'OK',
    confirmText: 'Conferma',
  },
  colorPicker: {
    placeholder: 'Inserisci',
  },
  upload: {
    dropActive: 'Rilascia per iniziare il caricamento',
    click: 'Clicca per caricare, ',
    paste: 'incolla, ',
    drag: 'o trascina i file qui',
    accept: 'Supporta il caricamento di {accept}',
    limit: 'È possibile caricare un massimo di {limit} file',
    maxFileSize: 'Ogni file non deve superare {maxFileSize}',
    pending: 'In attesa',
    success: 'Caricamento riuscito',
    fail: 'Caricamento fallito',
    uploading: 'Caricamento in corso',
    complete: 'Caricato',
    wrong_type: 'Formato non valido',
    wrong_size: 'Dimensione del file supera il limite',
  },
  pagination: {
    pageSize: '{pageSize} per pagina',
    jumpTo: 'Pag.',
    jumpConfirm: 'Vai',
    summary: 'Pagina {current} di {totalPages} · {total} elementi',
    perPage: 'Per pagina',
    prevSection: 'Pagine precedenti',
    nextSection: 'Pagine successive',
    navLabel: 'Paginazione',
    jumpGroup: 'Vai a pagina',
    prevPage: 'Pagina precedente',
    nextPage: 'Pagina successiva',
  },
  contextMenu: {
    noActions: 'Nessuna azione disponibile',
  },
  empty: {
    title: 'Nessun dato',
  },
}
