export default {
  name: 'zh',
  image: {
    fail: '暂时无法加载图片，请稍后再试',
  },
  input: {
    placeholder: '请输入',
    copy: '复制',
    copySuccess: '已复制到剪贴板',
    copyFailed: '复制未成功，请重试',
  },
  inputTag: {
    placeholder: '输入标签后按回车添加',
    maxLength: '已达到 {maxLength} 个标签上限，删除一些标签后即可继续添加',
    duplicate: '已存在相同标签，请输入新的标签',
  },
  select: {
    placeholder: '请选择',
    resultCount: '共 {num} 条结果',
    noResult: '暂无结果',
    searchPlaceholder: '输入搜索关键词',
  },
  selectMultiple: {
    placeholder: '请选择',
    resultCount: '共 {num} 条结果',
    noResult: '暂无结果',
    searchPlaceholder: '输入搜索关键词',
  },
  cascader: {
    placeholder: '请选择',
    closeText: '关闭',
    okText: '确定',
    noResult: '暂无结果',
  },
  tree: {
    resultCount: '共 {num} 条结果',
    noResult: '暂无结果',
    searchPlaceholder: '输入搜索关键词',
  },
  treeSelect: {
    placeholder: '请选择',
  },
  textarea: {
    placeholder: '请输入',
    resizeHandle: '拖动调整大小',
  },
  inputNumber: {
    placeholder: '请输入',
  },
  datePicker: {
    Mon: '一',
    Tue: '二',
    Wed: '三',
    Thu: '四',
    Fri: '五',
    Sat: '六',
    Sun: '日',
    Jan: '一月',
    Feb: '二月',
    Mar: '三月',
    Apr: '四月',
    May: '五月',
    Jun: '六月',
    Jul: '七月',
    Aug: '八月',
    Sep: '九月',
    Oct: '十月',
    Nov: '十一月',
    Dec: '十二月',
    placeholder: '选择日期',
  },
  dateRangePicker: {
    placeholderStart: '开始日期',
    placeholderEnd: '结束日期',
  },
  drawer: {
    closeText: '关闭',
    okText: '确定',
    confirmText: '确认',
  },
  modal: {
    closeText: '关闭',
    okText: '确定',
    confirmText: '确认',
  },
  dialog: {
    cancelText: '取消',
    okText: '确定',
    confirmText: '确认',
  },
  popok: {
    cancelText: '取消',
    okText: '确定',
    confirmText: '确认',
  },
  colorPicker: {
    placeholder: '请输入',
  },
  upload: {
    dropActive: '松开即可开始上传',
    click: '点击上传、',
    paste: '粘贴、',
    drag: '或将文件拖到这里',
    accept: '支持上传 {accept}',
    limit: '最多可上传 {limit} 个文件',
    maxFileSize: '单个文件不超过 {maxFileSize}',
    pending: '待上传',
    success: '上传成功',
    fail: '上传失败',
    uploading: '上传中',
    complete: '已上传',
    wrong_type: '非法格式',
    wrong_size: '文件大小超出限制',
  },
  pagination: {
    pageSize: '{pageSize} 条/页',
    jumpTo: '页码',
    jumpConfirm: '跳转',
    summary: '第 {current} / {totalPages} 页，共 {total} 条',
    perPage: '每页',
    prevSection: '更多前面的页码',
    nextSection: '更多后面的页码',
    navLabel: '分页导航',
    jumpGroup: '跳转到指定页',
    prevPage: '上一页',
    nextPage: '下一页',
  },
  contextMenu: {
    noActions: '暂无操作',
  },
  empty: {
    title: '暂无数据',
  },
}
